import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Dal Makhani, Butter Paneer & Paratha",
    Cal:620,
    nutrition: "High Protein",
    veg:true,
    price: 213,
    rating:3.9,
    bestseller:true,
    image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6215/primary/4_1.jpg",
    categoryName: "Thali",
  },
  {
    _id: uuid(),
    title: "Butter Chicken & Paratha",
    Cal:800,
    nutrition: "High Protein",
    veg:false,
    
    rating:3.9,
    bestseller:true,
    image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6262/primary/2_1.jpg",
    price: 212,
    categoryName: "Thali",
  },
  {
    _id: uuid(),
    title: "Chana Masala & 2 Kulche",
    Cal:589,
    nutrition: "High Protein",
    veg:true,
    
    rating:3.9,
    bestseller:true,
    image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6238/primary/2_1.jpg",
    price: 151,
    categoryName: "Thali",
  },
  {
    _id: uuid(),
    Cal:763,
    title: "Moong Dal,Paneer Kadhai & Tawa Roti",
    nutrition: "High Protein",
    veg:true,
    rating:3.9,
    bestseller:true,
    image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6439/primary/2_1.jpg",
    price: 249,
    categoryName: "Thali",
  },
  {
    _id: uuid(),
    title: "Keema Chicken, Moong Dal & Paratha",
    Cal:620,
    nutrition: "High Protein",
    veg:false,
    rating:3.9,
    bestseller:true,
    image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6441/primary/2_1.jpg",
    price: 213,
    categoryName: "Thali",
  },

// Khichdi
{
  _id: uuid(),
  title: "Vegetable Khichdi",
  Cal:372,
  nutrition: "High Protein",
  veg:true,
  rating:3.9,
  bestseller:true,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/GIK39/primary/1_1.jpg",
  price: 116,
  categoryName: "Khichdi",
},
{
  _id: uuid(),
  title: "Dal Palak Khichdi",
  Cal:506,
  nutrition: "High Protein",
  veg:true,
  rating:3.9,
  bestseller:false,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/GIK52/primary/1_1.jpg",
  price: 177,
  categoryName: "Khichdi",
},
{
  _id: uuid(),
  title: "Garlic Tadka Khichdi",
  Cal:455, 
  nutrition: "Low Calorie",
  veg:true,
  rating:3.9,
  bestseller:false,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/GIK54/primary/1_1.jpg",
  price: 116,
  categoryName: "Khichdi",
},
{
  _id: uuid(),
  title: "Dal Palak Khichdi (500gm)",
  Cal:506, 
  nutrition: "Iron Rich",
  veg:true,
  rating:3.9,
  bestseller:false,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6344/primary/6_1.jpg",
  price: 204,
  categoryName: "Khichdi",
},
{
  _id: uuid(),
  title: "Achari Khichdi",
  Cal:413, 
  nutrition: "Low Calorie",
  veg:true,
  rating:3.9,
  bestseller:false,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6653/primary/2_1.jpg",
  price: 133,
  categoryName: "Khichdi",
},
 //pizza
 {
  _id: uuid(),
  title: "8' Farm Fresh Veggie Pizza",
  Cal:595, 
  nutrition: "High Carb",
  veg:true,
  rating:3.9,
  bestseller:false,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6618/primary/4_1.jpg",
  price: 257,
  categoryName: "Pizza",
},
{
  _id: uuid(),
  title: "8' Indie Chicken Tikka Pizza",
  Cal:595, 
  nutrition: "High Carb",
  veg:false,
  rating:3.9,
  bestseller:true,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6393/primary/4_1.jpg",
  price: 657,
  categoryName: "Pizza",
},
{
  _id: uuid(),
  title: "8' Classic Paneer Pizza",
  Cal:672, 
  nutrition: "Medium Protein",
  veg:true,
  rating:3.9,
  bestseller:true,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6394/primary/4_1.jpg",
  price: 258,
  categoryName: "Pizza",
},
{
  _id: uuid(),
  title: "Whole Wheat Garlic Bread",
  Cal:308, 
  nutrition: "Medium Carb ",
  veg:true,
  rating:3.9,
  bestseller:false,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6719/primary/1_1.jpg",
  price: 99,
  categoryName: "Pizza",
},
{
  _id: uuid(),
  title: "8' Double Cheese Margherita Pizza",
  Cal:625, 
  nutrition: "High Carb, Fat",
  veg:true,
  rating:3.9,
  bestseller:true,
  image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/w_295,ar_1.33,fl_progressive,f_auto,q_auto:eco/dpr_2/image/singles/eat/meals/EAT6545/primary/4_1.jpg",
  price: 266,
  categoryName: "Pizza",
},
];
